load("@prysm//tools/go:def.bzl", "go_library", "go_test")

go_library(
    name = "go_default_library",
    srcs = [
        "rewards.go",
        "tracker.go",
    ],
    importpath = "github.com/OffchainLabs/prysm/v7/beacon-chain/core/timeliness",
    visibility = ["//visibility:public"],
    deps = [
        "//beacon-chain/core/helpers:go_default_library",
        "//beacon-chain/state:go_default_library",
        "//beacon-chain/core/time:go_default_library",
        "//config/params:go_default_library",
        "//consensus-types/primitives:go_default_library",
        "//time/slots:go_default_library",
        "@com_github_sirupsen_logrus//:go_default_library",
    ],
)

go_test(
    name = "go_default_test",
    srcs = ["tracker_test.go"],
    deps = [
        ":go_default_library",
        "//config/params:go_default_library",
        "//consensus-types/primitives:go_default_library",
        "//testing/require:go_default_library",
    ],
)
